spring.application.name=Contact-Management


spring.datasource.url=${CONTACT_MANAGEMENT_DB_HOST}
spring.datasource.username=${CONTACT_MANAGEMENT_DB_USER}
spring.datasource.password=${CONTACT_MANAGEMENT_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect